apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portMaster }}
      targetPort: {{ .Values.service.portMaster }}
      name: master
    - port: {{ .Values.service.portSlave }}
      targetPort: {{ .Values.service.portSlave }}
      name: slave
  selector:
    app: {{ .Chart.Name }}
