# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jfrog.it-academy.by/public/jenkins-ci
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "inemkovich"

fullnameOverride: "jenkins"

service:
  type: ClusterIP
  portMaster: 8080
  portSlave: 50000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "jenkins.k8s-36.sa"
  hosts:
    - host: jenkins.k8s-35.sa
      paths:
        - path: /
          pathType: Prefix
          
resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 1000m
    memory: 1000Mi

volumeMounts:
  - name: jenkins-auth-config
    mountPath: /var/jenkins_home/init.groovy.d/basic-security.groovy
    subPath: basic-security.groovy
  - name: jenkins-config-yaml
    mountPath: /var/jenkins_home/casc_configs/jenkins.yaml
    subPath: jenkins.yaml
  - name: jenkins-config
    mountPath: /var/jenkins_home

volumes:
  - name: jenkins-auth-config
    configMap:
      name: basic-security
  - name: jenkins-config-yaml
    configMap:
      name: jenkins-config
  - name: jenkins-config
    nfs:
      server: 192.168.37.105
      path: /mnt/IT-Academy/nfs-data/sa2-20-22/Ivan_Nemkovich/jenkins

autoscaling:
  enabled: false
