name: Validation by kubeval

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in dir1 and dir2
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: Ivan_Nemkovich/07.Ansible.Workshop/roles/redmine/tasks/main.yml
          comment: false
