# This is a workflow to do 04.GitOps homework

name: 04.GitOps

on:
  pull_request:
    branches: [ master ]

jobs:
  count_tabs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Find TABs
        run: grep -r $'\t' . > tab_log.txt
  
  create_log:
    runs-on: ubuntu-latest
    needs: [count_tabs]

    steps:
      - name: Upload artifact
        uses: upload-artifact@v3.0.0
        with:
          path: tab_log.txt
