---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-pv
  labels:
    type: nfs
    name: project-nfs-vol
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/IT-Academy/nfs-data/sa2-20-22/Ivan_Nemkovich/project
    server: 192.168.37.105